// Mock data for Mesa prototype

window.UNIVERSITIES = [
  { id: 'u1', name: 'Pomona College', state: 'Claremont, CA', size: 'Small · 1,700', tuition: '$$$$', band: 'high', tags: ['liberal arts','residential','close-knit'], score: 96,
    why: 'Small, tight-knit liberal arts feel matches how you described your ideal day. Strong creative writing + neuroscience overlap.' },
  { id: 'u2', name: 'Oberlin College', state: 'Oberlin, OH', size: 'Small · 2,900', tuition: '$$$', band: 'mid', tags: ['arts-forward','progressive','music'], score: 93,
    why: 'Music double-degree pathway fits your hobby interest. Campus culture leans quietly creative, which is your vibe.' },
  { id: 'u3', name: 'UC Santa Cruz', state: 'Santa Cruz, CA', size: 'Mid · 19k', tuition: '$$', band: 'low', tags: ['nature','quirky','marine bio'], score: 91,
    why: 'Redwoods and coastline for the outdoors answer. Large enough to find niches, small enough to be found.' },
  { id: 'u4', name: 'Macalester College', state: 'St. Paul, MN', size: 'Small · 2,100', tuition: '$$$', band: 'mid', tags: ['international','urban-adjacent','civic'], score: 89,
    why: 'You wanted a college town next to a real city. St. Paul delivers. Global studies is a strong thread here.' },
  { id: 'u5', name: 'Bowdoin College', state: 'Brunswick, ME', size: 'Small · 1,900', tuition: '$$$$', band: 'high', tags: ['coastal','outdoorsy','traditional'], score: 87,
    why: 'Outdoor Orientation Trips are legendary. Coastal Maine and a small campus suits your described rhythm.' },
  { id: 'u6', name: 'Kenyon College', state: 'Gambier, OH', size: 'Small · 1,800', tuition: '$$$', band: 'mid', tags: ['writing','rural','literary'], score: 85,
    why: 'Literary reputation aligns with your major interests. Tiny town, big creative energy.' },
  { id: 'u7', name: 'Reed College', state: 'Portland, OR', size: 'Small · 1,500', tuition: '$$$$', band: 'high', tags: ['intellectual','independent','thesis'], score: 82,
    why: 'Senior thesis + pass/fail freshman year attracts students who like how you think.' },
  { id: 'u8', name: 'University of Vermont', state: 'Burlington, VT', size: 'Mid · 11k', tuition: '$$', band: 'low', tags: ['outdoorsy','environmental','public'], score: 78,
    why: 'Public, affordable, and outdoor-forward. Would stretch you socially in a good way.' },
];

window.FRIENDS = [
  { id: 'f1', name: 'Maya R.', age: 18, initials: 'MR', school: 'Pomona College (committed)', origin: 'from Oakland, CA',
    bio: "Looking for someone to go on weird museum trips with. Also, please convince me to stop buying records.",
    interests: ['creative writing', 'film photography', 'hiking', 'jazz', 'cooking together'],
    goals: ['find a study partner', 'make a close friend group', 'try intramural soccer'],
    compat: 93,
    shared: ['Pomona College', 'creative writing', 'hiking'],
    reason: "You both picked <b>Pomona</b> and said <b>creative writing</b> matters. Maya also wants the same small study group you do.",
    tone: 'sage' },
  { id: 'f2', name: 'Jordan T.', age: 18, initials: 'JT', school: 'Oberlin College (interested)', origin: 'from Austin, TX',
    bio: "I run on oat lattes and sight-reading. Would love a friend who remembers to actually eat dinner during finals.",
    interests: ['piano', 'thrifting', 'linguistics', 'running', 'coffee shops'],
    goals: ['music ensemble friends', 'quiet study buddies', 'find a co-op house'],
    compat: 88,
    shared: ['Oberlin', 'music', 'quiet study'],
    reason: "Shared pick of <b>Oberlin</b> and both of you said a quieter social style. Jordan plays piano, and you mentioned wanting music friends.",
    tone: 'sand' },
  { id: 'f3', name: 'Sam P.', age: 19, initials: 'SP', school: 'UC Santa Cruz (committed)', origin: 'from San Diego, CA',
    bio: "Tide-pool enthusiast, amateur baker, reluctant morning person. Always game for a beach day before a problem set.",
    interests: ['marine biology', 'baking sourdough', 'surfing', 'board games', 'hiking'],
    goals: ['lab partners', 'weekend adventure crew', 'housing for sophomore year'],
    compat: 85,
    shared: ['UC Santa Cruz', 'hiking', 'coastal'],
    reason: "Both chose <b>UC Santa Cruz</b> as a top pick and listed <b>outdoors</b> as a must. Sam is also looking for a weekend crew.",
    tone: 'sage' },
  { id: 'f4', name: 'Priya K.', age: 18, initials: 'PK', school: 'Macalester College (interested)', origin: 'from Minneapolis, MN',
    bio: "Global studies bound, international food fanatic. Will bring snacks to every study session, this is a promise.",
    interests: ['global studies', 'running', 'podcasts', 'museums', 'pickup soccer'],
    goals: ['join a cultural org', 'run a half-marathon', 'close-knit friends'],
    compat: 81,
    shared: ['Macalester', 'soccer', 'civic-minded'],
    reason: "Shared <b>Macalester</b> pick, both said you want a <b>close-knit</b> group. Priya wants the same civic-minded org scene you do.",
    tone: 'sand' },
  { id: 'f5', name: 'Theo W.', age: 18, initials: 'TW', school: 'Pomona College (interested)', origin: 'from Chicago, IL',
    bio: "Neuro major hopeful. I draw comics in lecture. Looking for the kind of friends who text you at 1am about a new idea.",
    interests: ['neuroscience', 'comics', 'climbing', 'board games', 'late-night diners'],
    goals: ['research partner', 'climbing gym crew', 'start a zine'],
    compat: 79,
    shared: ['Pomona', 'neuro', 'late nights'],
    reason: "Same <b>Pomona</b> pick and <b>neuroscience</b> interest. Theo's 'start a zine' matches your creative writing.",
    tone: 'clay' },
];

window.POSTS = [
  { id: 'p1', author: 'Maya R.', initials: 'MR', school: 'Pomona',
    title: 'Looking for a weekend hiking crew (no competitive vibes)',
    body: "I want to get off campus most Saturdays. Claremont has good trails within 30 min. Easy pace, good snacks, no one training for anything. Bonus if you like taking bad photos of lizards.",
    tags: ['hiking', 'weekends', 'no-pressure'],
    when: '2h ago', saves: 14, replies: 3 },
  { id: 'p2', author: 'Jordan T.', initials: 'JT', school: 'Oberlin',
    title: 'Premed study group that actually shows up',
    body: "Starting gen chem in fall. Looking for 3–4 people to meet twice a week. Not the vibe where we open books and scroll phones. Serious but kind.",
    tags: ['premed', 'study group', 'chem'],
    when: '5h ago', saves: 22, replies: 6 },
  { id: 'p3', author: 'Sam P.', initials: 'SP', school: 'UC Santa Cruz',
    title: 'Early-morning surf friends before classes start',
    body: "Moving in 3 weeks. I'd love to meet a couple of people who want to be in the water by 7am most days. I can bring extra wax and bad jokes.",
    tags: ['surf', 'mornings', 'ocean'],
    when: '1d ago', saves: 31, replies: 9 },
  { id: 'p4', author: 'Priya K.', initials: 'PK', school: 'Macalester',
    title: 'International potluck, monthly, my place',
    body: "Every month someone hosts and cooks something from home. Aiming to start in September. Not a club, just friends feeding friends.",
    tags: ['food', 'culture', 'monthly'],
    when: '2d ago', saves: 48, replies: 12 },
  { id: 'p5', author: 'Theo W.', initials: 'TW', school: 'Pomona',
    title: 'Starting a zine, looking for a co-editor',
    body: "Poetry + comics + campus weirdness. Two issues a semester, small print run. If you've ever made a chapbook, or always meant to, let's talk.",
    tags: ['writing', 'zine', 'creative'],
    when: '3d ago', saves: 19, replies: 5 },
];

window.QUIZ = [
  { id: 'q1', eyebrow: 'Question 01 · Academics',
    title: "What pulls you first: ideas, making, or helping?",
    hint: "Rough is fine. We'll get more specific later.",
    options: [
      { key:'A', label: 'Ideas & writing', desc: 'Humanities, social sciences, the arts' },
      { key:'B', label: 'Science & research', desc: 'Biology, chem, neuro, physics, math' },
      { key:'C', label: 'Making & building', desc: 'Engineering, CS, design, architecture' },
      { key:'D', label: 'People & systems', desc: 'Public health, policy, education, business' },
    ]},
  { id: 'q2', eyebrow: 'Question 02 · Scale',
    title: "How big should the campus feel?",
    hint: "Not final. Just your gut.",
    options: [
      { key:'A', label: 'Small, I want to know people', desc: 'Under 3,000 students' },
      { key:'B', label: 'Medium, room to meet new people', desc: '3,000 to 10,000' },
      { key:'C', label: 'Large, lots of overlapping worlds', desc: '10,000 to 25,000' },
      { key:'D', label: 'Very large, full city energy', desc: '25,000 and up' },
    ]},
  { id: 'q3', eyebrow: 'Question 03 · Place',
    title: "What kind of place do you want to wake up in?",
    hint: "Setting shapes your daily life more than people expect.",
    options: [
      { key:'A', label: 'Small college town', desc: 'Walkable, tight, quiet' },
      { key:'B', label: 'Near a real city', desc: 'College town with quick transit in' },
      { key:'C', label: 'In a city', desc: 'Urban energy, spread-out campus' },
      { key:'D', label: 'Nature on every side', desc: 'Trails, water, stars' },
    ]},
  { id: 'q4', eyebrow: 'Question 04 · Budget',
    title: "How important is cost in your decision?",
    hint: "Honest is helpful. We use it to balance reach and safety picks.",
    options: [
      { key:'A', label: 'Very. It shapes my list', desc: 'Prioritize affordable options and aid' },
      { key:'B', label: 'Somewhat. Aid makes or breaks it', desc: 'Open to pricier with the right package' },
      { key:'C', label: 'A little', desc: 'Consider it, but not leading' },
      { key:'D', label: 'Not really a factor', desc: 'Fit first, cost second' },
    ]},
  { id: 'q5', eyebrow: 'Question 05 · Vibe',
    title: "Pick the vibe that feels like home.",
    hint: "No wrong answer. Just closest to true.",
    options: [
      { key:'A', label: 'Quietly intellectual', desc: 'Books in coffee shops, long conversations' },
      { key:'B', label: 'Creative & expressive', desc: 'Art, music, shows on weekends' },
      { key:'C', label: 'Active & outdoorsy', desc: 'Trails, games, early mornings' },
      { key:'D', label: 'Social & spirited', desc: 'Big events, traditions, school pride' },
    ]},
  { id: 'q6', eyebrow: 'Question 06 · Social',
    title: "How do you make friends, usually?",
    hint: "This shapes who we surface for the Friends step.",
    options: [
      { key:'A', label: 'A few close people', desc: "I'd rather go deep with 3 than surface with 30" },
      { key:'B', label: 'A loose, wide crew', desc: 'Different people for different things' },
      { key:'C', label: 'Through shared activities', desc: 'Sports, clubs, projects' },
      { key:'D', label: 'Slowly, mostly through classes', desc: 'I warm up over a semester' },
    ]},
  { id: 'q7', eyebrow: 'Question 07 · Hobbies',
    title: "What do you want to keep doing in college?",
    hint: "Pick whichever rings loudest. We'll surface people who share it.",
    options: [
      { key:'A', label: 'Writing / reading / film', desc: 'Quieter creative pursuits' },
      { key:'B', label: 'Music / art / performance', desc: 'Makers and doers' },
      { key:'C', label: 'Outdoors / movement / sport', desc: 'Trails, courts, studios' },
      { key:'D', label: 'Building / tinkering / gaming', desc: 'Code, games, side projects' },
    ]},
  { id: 'q8', eyebrow: 'Question 08 · What matters most',
    title: "What would make this year feel like a win?",
    hint: "Last one. Pick the closest.",
    options: [
      { key:'A', label: 'A handful of real friends', desc: "People I'd text at 1am" },
      { key:'B', label: 'Figuring out what I want to study', desc: 'Clarity on a direction' },
      { key:'C', label: 'Finding a community or crew', desc: 'A club, team, or house that feels like mine' },
      { key:'D', label: 'Feeling like myself, more often', desc: 'Room to try things on' },
    ]},
];
